//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataLogic.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ålder.
        /// </summary>
        public static string Ålder {
            get {
                return ResourceManager.GetString("Ålder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kön.
        /// </summary>
        public static string Kön {
            get {
                return ResourceManager.GetString("Kön", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Profil.
        /// </summary>
        public static string Min_Profil {
            get {
                return ResourceManager.GetString("Min_Profil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mina Vänner.
        /// </summary>
        public static string Mina_Vänner {
            get {
                return ResourceManager.GetString("Mina_Vänner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sök Användare.
        /// </summary>
        public static string Sök_Användare {
            get {
                return ResourceManager.GetString("Sök_Användare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stad.
        /// </summary>
        public static string Stad {
            get {
                return ResourceManager.GetString("Stad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synlighet.
        /// </summary>
        public static string Synlighet {
            get {
                return ResourceManager.GetString("Synlighet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vänförfrågningar.
        /// </summary>
        public static string Vänförfrågningar {
            get {
                return ResourceManager.GetString("Vänförfrågningar", resourceCulture);
            }
        }
    }
}
